<template>
  <div>
    <h2>购物车</h2>
    <ul>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
      <li>好好好好</li>
    </ul>
  </div>

</template>

<script>
    export default {
        name: "Cart"
    }
</script>

<style scoped>

</style>
